package yonsei.xdesign.tochelin;

public class IntentKeyMap {
    public static String INTENT_KEY_MAIN_TO_SEARCH_QUERY_KEY = "INTENT_KEY_MAIN_TO_SEARCH_QUERY_KEY";
    public static String INTENT_KEY_SEARCH_TO_RESTAURANT_DETAIL_RESTAURANT_KEY = "INTENT_KEY_SEARCH_TO_RESTAURANT_DETAIL_RESTAURANT_KEY";
    public static String INTENT_KEY_RESTAURANT_DETAIL_TO_STAT_DETAIL_RESTAURANT_KEY = "INTENT_KEY_RESTAURANT_DETAIL_TO_STAT_DETAIL_RESTAURANT_KEY";
    public static String INTENT_KEY_RESTAURANT_DETAIL_TO_STAT_DETAIL_STAT_KEY = "INTENT_KEY_RESTAURANT_DETAIL_TO_STAT_DETAIL_STAT_KEY";
}
